name: Continuous Integration

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - .github/**
      - dist/**
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    if: ${{ !(github.event_name == 'pull_request_target' && startsWith(github.event.pull_request.head.ref, 'refs/heads/dependabot/')) }}
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    if: ${{ !(github.event_name == 'pull_request_target' && startsWith(github.event.pull_request.head.ref, 'refs/heads/dependabot/')) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Test Local Action and Send Discord Notification
        id: test-action
        uses: ./
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Test message from GitHub Actions'
          show_payload: 'true'
