name: Dependabot transpile code
on:
  push:
    branches:
      - dependabot/**  # Match branches created by Dependabot

permissions:
  contents: write

jobs:
  transpile:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository.
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # Setup Node.js using the version specified in `.node-version`.
      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      # Install dependencies using `npm ci`.
      - name: Install Dependencies
        id: install
        run: npm ci

      # Build the `dist/` directory.
      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      - name: Commit Changes to dist/
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[dependabot skip] chore(deps): update dist/ directory'

      - name: Run Check Dist
        uses: ${{ github.repository }}/.github/workflows/check-dist.yml@${{ github.ref}}
