name: Test Action

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - .github/**
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false  

      - name: Test Local Action and Send Discord Notification
        id: test-action
        uses: ./
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Test message from GitHub Actions'
          show_payload: 'true'
